name: Deploy Product Server


on:
  push:
    branches:
      -main

# on:
#   workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy
        run: 
          cd /var/www/battle-cards-server
          git pull origin main 
          


  # test:
  #   runs-on: self-hosted

  #   steps:
  #     - run: echo "Hello Runner"
  #     - run: whoami
  #     - run: pwd